---
title: "Policies"
---

## Workload expectations

-   This is a 4-credit hour course, so you should expect to complete \~ 120 hours of work for the course—an average, or about 12 hours each week (this includes time in-class).

-   My estimate for time usage for activities and assignments in an average week is below – some weeks may have shorter or longer time commitments either by design or due to course scheduling.

    | Activity                                      | Hours per Week |
    |-----------------------------------------------|:--------------:|
    | In-class meetings                             |      3-4       |
    | Pre-class reading                             |       4        |
    | Informal exercises                            |       1        |
    | Homework assignments                          |       2        |
    | Research, drafting, editing for final project |       1        |
    | TOTAL                                         |       12       |

## Communication

### *Electronic*

-   Our class will communicate through our Canvas site. Announcements and emails are archived there, automatically forwarded to your UO email, and can even reach you by text. Check and adjust your settings under Account \> Notifications.
-   We will also be using this GitHub Pages website ([https://wcresko.github.io/BioE_Stats_Wi2026/](https://wcresko.github.io/BioE_Stats/){.uri}) for the course as the repository for lecture schedule, syllabus, lecture slides and other materials.
-   Every Monday I will post an Announcement that previews critical concepts we’ll work on that week and a checklist of the week’s due dates.
-   I will contact individual students when needed through email, and I try to respond to questions within one business day.
-   When giving feedback on assignments, I do so in Canvas, and turnaround time for feedback is generally one week.

### *Office hours*

-   I will host office hours each week on Monday and from 3:30 to 4:30. The end of many class periods will also function as a form of office hour.
-   I welcome meetings outside my regular office hours as well - please email me to set a time.
-   During office hours, students bring in a wide range of concerns, questions, and successes. We might
    -   talk through a specific concept or problem to clarify it
    -   think together about an issue a student is curious about that relates to the class
    -   discuss a student’s post-graduation goals
    -   identify more supportive methods to study for a future exam or to begin a project
    -   or any number of other topics

## Classroom Community Expectations

### *Participate and Contribute*:

All students are expected to participate by sharing ideas and contributing to the learning environment. This entails preparing, following instructions, and engaging respectfully and thoughtfully with others. While all students should participate, participation is not just talking, and a range of participation activities support learning. Participation might look like speaking aloud in the full class and in small groups, and working collaboratively on coding projects. We will establish more specific participation guidelines and criteria for contributions in our first weeks of the term.

### *Expect and Respect Diversity*

All classes at the University of Oregon welcome and respect diverse experiences, perspectives, and approaches. What is not welcome are behaviors or contributions that undermine, demean, or marginalize others based on race, ethnicity, gender, sex, age, sexual orientation, religion, ability, or socioeconomic status. We will value differences and communicate disagreements with respect. We may establish more specific guidelines and protocols to ensure inclusion and equity for all members of our learning community.

### *Help Everyone Learn*

Part of how we learn together is by learning from one another. To do this effectively, we need to be patient with each other, identify ways we can assist others, and be open-minded to receiving help and feedback from others. Don’t hesitate to contact me to ask for assistance or offer suggestions that might help us learn better.

## Generative Artificial Intelligence (GenAI) Use

Students can use GenAI tools in this class to help with certain aspects of coding. We will discuss during the first week how GenAI can be a tool to help you, but it cannot replace your statistical intuition and knowledge. However, you cannot use content such as text, graphics and code created by GenAI tools in your work. You must be the author/creator of your work submissions. For example, you can use a GenAI tool to suggest a paper outline based on a draft you provide it, or suggest some code, but you cannot submit a paper with text or code generated by GenAI as if the text or code is your own writing. If you are in doubt or have questions about a particular GenAI tool and if its use is okay, check in with me and let’s discuss!

## University Course Policies

Please read and make sure you are familiar with the important policies that apply to all UO courses, which can be found [here.](https://teaching.uoregon.edu/university-course-policies)
